[build]
  publish = "."   # use current root, where index.html is

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  [functions.stale-issues]
    schedule = "2 2 * * *" # Optional: only if you want CRON job
